Improvements
Pass argument to smallify
-r : replace files
-f : optional output folder

pass arguments -r or -f folder

Replace magick by convert

remove .py

Better help.

Docstring

diff --git a/smallify b/smallify
--- a/smallify
+++ b/smallify
@@ -4,8 +4,66 @@ FILE="$1"
 QUALITY="$2"
 MAXHEIGHT=$3
 
+REPLACE=1 # 1 is False
+WORKING="Working"
+FOLDER="Smaller_comics"
 PORTRAITSIZE=1000  # in ko
 PAYSAGESIZE=2000  # in ko
+
+usage="$(cat <<-EOF
+$(basename "$0") file quality height [-h] [-r] [-f folder]
+Example :
+$(basename "$0") myfile.cbz 70 1920
+
+By default, it saves smallified comics in 'Smaller_comics' default folder.
+
+$(basename "$0") myfile.cbz 70 1920 -r
+will REPLACE your comics ! Be careful !!
+
+$(basename "$0") myfile.cbz 70 1920 -f \"my smaller comics\"
+will save your smallified comics in \"my smaller comics\"
+
+where:
+    -h              show this help text
+    -r, --replace   set the 'Replace' flag on ! It replace your comics !
+                    Be very careful with this
+    -f, --folder    set the folder where to save smallified comics
+EOF
+)"
+
+shift 3
+while :; do
+    case $1 in
+        -h|-\?|--help)
+            #show_help    # Display a usage synopsis.
+            echo "$usage"
+            exit
+            ;;
+	    -r|--replace)       # Takes an option argument; ensure it has been specified.
+            REPLACE=0
+            ;;
+        -f|--folder)       # Takes an option argument; ensure it has been specified.
+            if [ "$2" ]; then
+                FOLDER="$2"
+                echo "Destination folder : '$FOLDER'"
+                shift
+            else
+                die 'ERROR: "--file" requires a non-empty option argument.'
+            fi
+            ;;
+        --)              # End of all options.
+            shift
+            break
+            ;;
+        -?*)
+            printf 'WARN: Unknown option (ignored): %s\n' "$1" >&2
+            ;;
+        *)               # Default case: No more options, so break out of the loop.
+            break
+    esac
+
+    shift
+done
 
 function unarchive-comic {
     # If / Elif : unarchive file (rar or zip)
@@ -13,9 +71,9 @@ function unarchive-comic {
     if [[ $(file --mime-type -b "$FILE") == application/x-rar ]]; then
         echo "$FILE is rared"
         DIR="${FILE%.*}"
-        mkdir "$DIR"
+        mkdir -p "$WORKING/$DIR"
         echo "Extraction de $FILE"
-        unrar x ./"$FILE" -o "$DIR" -idq
+        unrar x ./"$FILE" -o "$WORKING/$DIR" -idq
 
     # Test if archive is ZIP
     elif [[ $(file --mime-type -b "$FILE") == application/zip ]]; then
@@ -25,9 +83,9 @@ function unarchive-comic {
         zip -d "$FILE" "*.DS_Store" &>/dev/null
         zip -d "$FILE" "*desktop.ini" &>/dev/null
         DIR="${FILE%.*}"
-        mkdir "$DIR"
+        mkdir -p "$WORKING/$DIR"
         echo "Extraction de $FILE"
-        unzip -q "$FILE" -d "$DIR"
+        unzip -q "$FILE" -d "$WORKING/$DIR"
     else
         echo "$FILE is not RAR or ZIP"
         exit 1
@@ -41,7 +99,7 @@ function smallify-jpeg {
     SIZE=$(du -k "$IMG" | cut -f1)
     PORTRAIT=true
     if (( $HEIGHT > $WIDTH )); then PORTRAIT=true; else PORTRAIT=false; fi
-    echo "Dimensions : $WIDTH x $HEIGHT. Poids = $SIZE ko" Portrait ? $PORTRAIT
+    # echo "Dimensions : $WIDTH x $HEIGHT. Poids = $SIZE ko" Portrait ? $PORTRAIT
     if $PORTRAIT ; then
         # echo portrait
         MAXSIZE=$PORTRAITSIZE
@@ -53,17 +111,18 @@ function smallify-jpeg {
     # HEIGHT > MAX and SIZE > MAX ?
     if [[ $HEIGHT -gt $MAXHEIGHT && $SIZE -gt $MAXSIZE ]]; then
         # echo "magick size and quality !"
-	    magick "$IMG" -quality $QUALITY -geometry x$MAXHEIGHT "$IMG"
+	    convert "$IMG" -quality $QUALITY -geometry x$MAXHEIGHT "$IMG"
     # HEIGHT > MAX but SIZE already ok ?
     elif [[ $HEIGHT -gt $MAXHEIGHT && $SIZE -le $MAXSIZE ]]; then
         # echo "magick size only"
-        magick "$IMG" -geometry x$MAXHEIGHT "$IMG"
+        convert "$IMG" -geometry x$MAXHEIGHT "$IMG"
     # HEIGHT is ok (< MAX) but SIZE is too big ?
     elif [[ $SIZE -gt $MAXSIZE ]]; then
         # echo "magick quality only"
-        magick "$IMG" -quality $QUALITY "$IMG"
+        convert "$IMG" -quality $QUALITY "$IMG"
     else
-        echo "Nothing to do, jpeg already small"
+        # echo "Nothing to do, jpeg already small"
+        :
     fi
 }
 
@@ -72,28 +131,28 @@ function smallify-png {
     HEIGHT=$(identify -format "%h" "$IMG")> /dev/null
     if [[ $HEIGHT > $MAXHEIGHT ]]; then
         echo "magick size only (png)"
-        magick "$IMG" -geometry x$MAXHEIGHT "$IMG"
+        convert "$IMG" -geometry x$MAXHEIGHT "$IMG"
     fi
 }
 
 function archive-comic {
     if [[ $FILE == *.cbz ]]; then
         echo "Création archive $FILE"
-        pushd "$DIR" 1>/dev/null || return
-        zip -q -r "../Smaller_comics/$FILE" *
+        pushd "$WORKING/$DIR" 1>/dev/null || return
+        zip -q -r "../../$FOLDER/$FILE" *
         popd 1>/dev/null || return
-        rm -r "$DIR"
+        rm -r "$WORKING/$DIR"
     elif [[ $FILE == *.cbr ]]; then
         echo "Création archive $FILE"
-        rar a -ma4 -r -ep1 "Smaller_comics/$FILE" "$DIR/" -idq
-        rm -r "$DIR"
+        rar a -ma4 -r -ep1 "$FOLDER/$FILE" "$WORKING/$DIR/" -idq
+        rm -r "$WORKING/$DIR"
     else
         echo "Fichier non pris en charge"
     fi
 }
 
 function check-comic {
-    pushd "Smaller_comics" 1>/dev/null || return
+    pushd "$FOLDER" 1>/dev/null || return
     # if [[ $FILE == *.cbz ]]; then
     if [[ $(file --mime-type -b "$FILE") == application/zip ]]; then
         if unzip -tq "$FILE"; then
@@ -108,7 +167,7 @@ function check-comic {
             return 1
         fi
     elif [[ $(file --mime-type -b "$FILE") == application/x-rar ]]; then
-        if unrar t "$FILE"; then
+        if unrar t "$FILE" -idq; then
             echo "$FILE is OK"
              # 0 = true
              popd 1>/dev/null || return
@@ -128,14 +187,14 @@ function check-comic {
 
 function move-comic {
     echo "moving $FILE"
-    mv -f Smaller_comics/"$FILE" .
+    mv -f "$FOLDER/$FILE" .
 }
 
 unarchive-comic
 
 # Smallify jpeg with Image Magick voodoo
 echo "Réduction des images"
-pushd "$DIR" 1>/dev/null || return
+pushd "$WORKING/$DIR" 1>/dev/null || return
 
 # smallify all jpg
 find . -type f -iname "*.jpg" -print0 | \
@@ -151,12 +210,20 @@ find . -type f -iname "*.png" -print0 | \
 
 popd 1>/dev/null || return
 
-mkdir -p "Smaller_comics"
+mkdir -p "$FOLDER"
 
 # make new archive
 archive-comic
 
-# Check integrity and move
-if check-comic; then move-comic; fi
+if [[ $REPLACE -eq 0 ]]; then
+    echo "Remplacement des fichiers !!!!"
+    # Check integrity and move
+    if check-comic; then move-comic; fi
+    rmdir "$FOLDER"
+else
+    if check-comic; then echo "Fichiers non remplacés, situés dans '$FOLDER'"; fi
+fi
 
-rmdir Smaller_comics
+
+# rmdir "$FOLDER"
+rmdir $WORKING
diff --git a/smallify-all b/smallify-all
--- a/smallify-all
+++ b/smallify-all
@@ -1,10 +1,79 @@
 #!/bin/bash
 
+REPLACE=1 # 1 is False
+
+usage="$(cat <<-EOF
+Example :
+$(basename "$0")
+
+By default, it saves smallified comics in 'Smaller_comics' default folder.
+
+$(basename "$0") -r or $(basename "$0") --replace
+will REPLACE your comics ! Be careful !!
+
+$(basename "$0") -f \"my smaller comics\"
+will save your smallified comics in \"my smaller comics\"
+
+$(basename "$0") [-h] [-r] [-f folder]
+where:
+    -h              show this help text
+    -r, --replace   set the 'Replace' flag on ! It replace your comics !
+                    Be very careful with this
+    -f, --folder    set the folder where to save smallified comics
+EOF
+)"
+
+while :; do
+    case $1 in
+        -h|-\?|--help)
+            #show_help    # Display a usage synopsis.
+            echo "$usage"
+            exit
+            ;;
+	    -r|--replace)       # Takes an option argument; ensure it has been specified.
+            REPLACE=0
+            ;;
+        -f|--folder)       # Takes an option argument; ensure it has been specified.
+            if [ "$2" ]; then
+                FOLDER="$2"
+                # echo "Destination folder : '$FOLDER'"
+                shift
+            else
+                die 'ERROR: "--file" requires a non-empty option argument.'
+            fi
+            ;;
+        --)              # End of all options.
+            shift
+            break
+            ;;
+        -?*)
+            printf 'WARN: Unknown option (ignored): %s\n' "$1" >&2
+            ;;
+        *)               # Default case: No more options, so break out of the loop.
+            break
+    esac
+
+    shift
+done
+
 for FILE in *{.cbr,.CBR,.cbz,.CBZ}
 do
-	[ -e "$FILE" ] || continue
+    # echo "smallify $FILE 70 1920 $params"
     # second argument is jpeg quality
     # third argument is the new height of pictures
-	smallify "$FILE" 70 1920
+	[ -e "$FILE" ] || continue
+    # Stupid mode, because folder is finally deleted in replace mode
+    if [[ $REPLACE -eq 0 && ! -z "$FOLDER" ]]; then
+        smallify "$FILE" 70 1920 -r -f "$FOLDER"
+    # Replace mode, -r option
+    elif [[ $REPLACE -eq 0 ]]; then
+        smallify "$FILE" 70 1920 -r
+    # No Replace mode, with custom folder
+    elif [ ! -z "$FOLDER" ]; then
+        smallify "$FILE" 70 1920 -f "$FOLDER"
+    # Default mode, no replace
+    else
+        smallify "$FILE" 70 1920
+    fi
 	echo "------------------------"
 done
